In [10]:
# Basic operation
import torch
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[2.0,1,4,5], [1,2,3,4],[4,3,2,1]])

x_ = torch.cat((x,y), dim=0)
y_ = torch.cat((x,y), dim=1)
y_

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  5.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [11]:
# board casting
a = torch.arange(3).reshape(1,3)
b = torch.arange(2).reshape(2,1)

a + b

tensor([[0, 1, 2],
        [1, 2, 3]])

In [5]:
# Linear regression scrath
# Y = W*X + B
import numpy as np
class LinearRegression:
    def __init__(self,lr = 1e-3, n_iter = 100):
        self.w = None
        self.b = None
        self.lr = lr
        self.iter = n_iter
    def fit(self, x, y):
        n_sample, n_feature = x.shape
        self.w = np.zeros(n_feature)
        self.b = 0.0
        for _ in range(self.iter):
            pre_y = x@self.w + self.b
            error = pre_y - y

            dw = (2/n_sample) * x.T@error
            db = (2/n_sample) * np.sum(error)

            self.w = self.w - self.lr * dw
            self.b -= self.lr * db
    
    def predict(self,x):
        return x@self.w + self.b


X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
    [5, 6]
])
y = np.array([5, 8, 11, 14, 17])  # 对应公式 y = 1*x1 + 2*x2 + 0

model = LinearRegression(1e-2,1000)
model.fit(X,y)

print(f'model w: {model.w}')
print(f'model b: {model.b}')
X_test = np.array([[6,7], [7,8]])
y_pred = model.predict(X_test)
print("Predictions:", y_pred)

        



model w: [1.33289628 1.66686716]
model b: 0.3339708814090338
Predictions: [19.9994187  22.99918214]


In [29]:
a.sum(axis=0,keepdim=True)

tensor([[[10, 12, 14, 16, 18],
         [20, 22, 24, 26, 28]]])

In [25]:
a.sum(axis=[0,1],keepdim=True)

tensor([[190]])

In [26]:
a.sum()

tensor(190)

In [15]:
import numpy as np
class Kmeans:
    def __init__(self, k_cluster, max_iter):
        self.k_cluster = k_cluster
        self.max_iter = max_iter
        self.center = None
        self.labels = None

    
    def fit(self, x):
        idx = np.random.choice(x.shape[0], self.k_cluster,replace=False)
        self.center = x[idx]

        for i in range(self.max_iter):
            # calculate distance for each sample to center
            diff = x[:,np.newaxis,:] - self.center[np.newaxis,:,:]
            dist = np.sqrt(np.sum(diff**2, axis=2))  # dist shape [x, k]
            # label for each example
            label = np.argmin(dist, axis=1)

            # new_centor
            new_center = np.zeros_like(self.center)
            for k in range(self.k_cluster):
                cluster_points = x[label==k]
                if len(cluster_points) > 0:
                    new_center[k] = np.mean(cluster_points, axis=0)
                else:
                    new_center[k] = self.center[k]
            
            shift = np.sqrt(np.sum((new_center - self.center)**2))
            if shift < 1e-4:
                break
            self.center = new_center

        self.labels = label
    
    def predit(self,x):
        diff = np.sqrt(np.sum((x[:,np.newaxis,:] - self.center[np.newaxis,:,:])**2, axis=2))
        return np.argmin(diff,axis=1)


X = np.array([
    [1, 2], [1.5, 1.8], [5, 8],
    [8, 8], [1, 0.6], [9, 11]
])

kmeans = Kmeans(2,100)
kmeans.fit(X)

print("Final centroids:\n", kmeans.center)
print("Labels:", kmeans.labels)



Final centroids:
 [[7.33333333 9.        ]
 [1.16666667 1.46666667]]
Labels: [1 1 0 0 1 0]
